[package]
name = "rust_web_template"
version = "0.1.0"
author = "{{author}}"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4"
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
tera = "1"
diesel = { version = "2.2.0", features = ["postgres"] }